Hiviexd/AxerBot

commands/fun/yesno.ts
events/messageCreate.ts
utils/messages/randomMessage.ts

moved random message function to its own file

refactor random message handling

---

types/score.ts
utils/osu/osuApiConnetion.ts

osuAPIConnection crash hotfix

---

commands/fun/quotes.ts
commands/fun/subcommands/quotesGetList.ts
commands/fun/subcommands/quotesGetStatus.ts
commands/fun/subcommands/quotesSetCustom.ts
commands/fun/subcommands/quotesSetDefault.ts
commands/fun/subcommands/quotesSetList.ts
commands/fun/subcommands/quotesSetWord.ts
commands/misc/help.ts
database/schemas/guild.ts
utils/messages/randomMessage.ts

fix the shit

---

commands/dev/serverlist.ts

remove boost count from serverlist

---

LICENSE
commands/fun/coinflip.ts
commands/fun/owoify.ts
commands/fun/revolver.ts
commands/fun/roll.ts
commands/index.ts
database/index.ts
database/migrations/addRevolverToGuildObject.ts
database/schemas/guild.ts
helpers/text/numberToEmoji.ts
package-lock.json
package.json

- coinflip
- roll
- revolver
- owoify (yep)

add a bunch of fun commands

---

.vscode/launch.json
commands/dev/repeat.ts
commands/index.ts
commands/management/purge.ts
commands/management/subcommands/cooldown/cooldownClear.ts
commands/management/subcommands/cooldown/cooldownRemove.ts
helpers/text/embeds/generateConfirmationEmbed.ts

should be easy to implement and customize confirmation embeds now, also reduced amount of copypasting letsgo

refactor command confirmation handling

---

helpers/text/osuTimestamp.ts

closes #108 
return message looks ugly but that's discord's fault, can't do anything about it for now.

support mania timestamps in osuTimestamp

---

commands/index.ts
commands/misc/reminder.ts
database/schemas/user.ts
events/ready.ts
helpers/reminder/remindersChecker.ts
helpers/reminder/timeChecker.ts

closes #41 
proud of this one
didn't test for dates that aren't in seconds, so I'd appreciate some testing with bigger dates

Add `reminder` command

---

README.md
commands/BNsite/bn.ts
commands/README.md
commands/index.ts
commands/misc/invite.ts
config.example.json
helpers/text/embeds/generateErrorEmbed.ts

documentation

---

commands/BNsite/openbns.ts
commands/index.ts
commands/misc/reminder.ts
helpers/osu/player/getHighestUsergroup.ts
helpers/qat/fetcher/qatAllUsers.ts
helpers/qat/fetcher/qatApi.ts
helpers/qat/getters/requestStatus/getOpenBNsPerMode.ts
helpers/qat/getters/requestStatus/getRequestStatus.ts
responses/qat/BNEmbed.ts
responses/qat/OpenBNsEmbed.ts
types/qat.ts

`-openbns` to view all open bns
`-openbns <gamemode>` to view open bns of a specific gamemode
data from bnsite

Add `openbns` command

---

commands/misc/reminder.ts
events/ready.ts

attempt to fix duplicate reminders

---

legal/PrivacyPolicy.md
legal/TermsOfService.md

add legal stuff

---

commands/BNsite/tracking.ts
helpers/qat/getters/preferences/getBNPreferences.ts
helpers/text/embeds/generateErrorEmbed.ts
helpers/text/embeds/generateSuccessEmbed.ts
modules/tracking/qatTracking.ts

add modes to bntracker embeds

---

helpers/qat/getters/preferences/getBNPreferences.ts

for some reason i forgot about those

add style preferences to bn tracker embed

---

commands/BNsite/tracking.ts
modules/downloader/beatmapDownloader.ts

make download prompts ephemeral

---

commands/BNsite/subcommands/tracker/addTrack.ts
responses/qat/BNEmbed.ts

resolves #176 
also removed qah info from /bn command because who cares about qah

limit args in modes in /bntrack

---

modules/tracking/qatTracking.ts

attempt at fixing bug that deletes bntrackers

---

events/guildMemberAdd.ts
events/guildMemberRemove.ts
events/messageDelete.ts
events/messageUpdate.ts
helpers/general/sendQuotes.ts
modules/loggers/logMessageDelete.ts
modules/loggers/logMessageEdit.ts
modules/loggers/logServerJoins.ts
modules/loggers/logServerLeaves.ts

gave rly old code a fresh coat of paint
made it modular instead of having the logging code in the events themselves
also bot now logs server joins for those interested (catch hub)

Refactor logging system

---

helpers/osu/url/checkOsuURL.ts
responses/osu/BeatmapsetDiscussionEmbed.ts

Fix discussion embed and add post location

---

commands/BNsite/subcommands/tracker/addTrack.ts
commands/BNsite/subcommands/tracker/removeTrack.ts
commands/BNsite/tracking.ts
commands/index.ts
commands/management/embeds.ts
commands/management/logging.ts
commands/management/osuTimestamps.ts
commands/management/purge.ts
commands/management/quotes.ts
commands/management/send.ts
commands/management/verification.ts
database/migrations/addCustomizationToLogging.ts
database/migrations/addOsuTimestamps.ts
database/schemas/guild.ts
helpers/core/slashCommandHandler.ts
helpers/osu/url/checkOsuURL.ts
helpers/text/embeds/generateMissingPermsEmbed.ts

/osutimestamps in order to enable or disable automatic timestamp parsing, enabled by default

add more control over osuTimestamps + big refactor

---

helpers/qat/getters/requestStatus/getOpenBNsPerMode.ts
helpers/text/numberToEmoji.ts
responses/qat/OpenBNsEmbed.ts

add count to openbns embed

---

modules/tracking/qatTracking.ts

on request
TODO: move the list to config.json so bot won't need an entire update for each change

opt out more BNs from tracking

---

commands/management/editMessage.ts

remove message from form placeholder

---

helpers/interactions/addPrivateRoles.ts

fix tfac role select not working

---

commands/BNsite/bn.ts
commands/user/mapper.ts
commands/user/mapsetrank.ts
commands/user/player.ts
commands/user/recent.ts
helpers/osu/player/getHighestUsergroup.ts
responses/osu/BeatmapsetDiscussionEmbed.ts

causing crashes rn when you use mapper/bn command on a spotlight curator

Support `BSC` in usergroup detection

---

commands/management/subcommands/verification/setButton.ts
commands/management/verification.ts
database/index.ts
database/migrations/addButtonToGuildVerification.ts
database/schemas/guild.ts
modules/loggers/logMessageDelete.ts
modules/loggers/logMessageEdit.ts
modules/loggers/logServerJoins.ts
modules/loggers/logServerLeaves.ts
modules/verification/client/StartVerification.ts

- added more info to loggers
- you can now disable the verification button from welcome messages, in case you want to use the verification system solely for its welcome message. use `/verification set button`

A couple requests from the osu!catch modding hub

---

commands/management/logging.ts
commands/management/subcommands/logging/disable.ts
commands/management/subcommands/logging/enable.ts
commands/management/verification.ts
modules/loggers/logMessageDelete.ts
modules/loggers/logMessageEdit.ts
modules/loggers/logServerJoins.ts
modules/loggers/logServerLeaves.ts
responses/qat/BNEmbed.ts

use /logging on a server you own/moderate to configure it

rewrite logging to slash

---

commands/index.ts
commands/management/subcommands/logging/disable.ts
commands/management/subcommands/logging/enable.ts
commands/management/subcommands/userLog/add.ts
commands/management/subcommands/userLog/remove.ts
commands/management/userLog.ts
database/schemas/guild.ts
helpers/qat/getters/resets/parseResets.ts
responses/osu/MapperEmbed.ts
responses/qat/BNEmbed.ts
types/user.ts

you can now add logs/notes about users for moderation purposes, consult this gif to see how to use it
https://nats.are-la.me/4GqDy4p.gif
also added total nom count to bn embed, and followers, subs, gd count and nom count to mapper embed

add user logging + more stats to mapper/bn embed

---

commands/management/userLog.ts

userlog permission hotfix

---

helpers/core/logger.ts
modules/reminders/remindersChecker.ts

bot shouldnt shit the bed now when a reminder is triggered on a deleted guild/channel/user (thanks mniam)

Fix error handling in reminders module

---

README.md
commands/BNsite/bn.ts
events/guildMemberAdd.ts

fixes the visual bug where the embed won't appear to new users unless they leave+rejoin or restart discord

add 1 second delay to welcome embed

---

helpers/osu/player/getHighestUsergroup.ts
responses/osu/MapperEmbed.ts
responses/osu/MapsetRankEmbed.ts
responses/osu/PlayerEmbed.ts
responses/qat/BNEmbed.ts

i LOVE discord making random changes to their api :trollface:

fix /mapper breaking on non usergrouped users

---

.prettierrc
modules/verification/client/StartVerification.ts

hid the button and adjusted the welcome message for servers that have `/verification set button` as `enabled`, will revert after we fix the verification server
if you want to switch back to your original welcome message but without the button, temporarily switch the above command to `disabled`

temporarily disable verification

---

.gitignore
commands/BNsite/bn.ts
commands/BNsite/bntracker.ts
commands/BNsite/openbns.ts
commands/fun/choose.ts
commands/general/ping.ts
commands/general/reminder.ts
commands/index.ts
commands/management/editMessage.ts
commands/management/sendMessage.ts
commands/management/subcommands/verification/setMessage.ts
commands/tools/resizebg.ts
commands/tools/spectro.ts
index.ts
modules/bancho/client.ts

too laze to describe what went on, just read the commit history :trollface:

General cleanups and fixes

---

helpers/text/osuTimestamp.ts

discord sucks so we gotta improvise /shrug

use embeds for osu timestamps

---

.prettierrc
constants/colors.ts
events/guildBanAdd.ts
events/guildBanRemove.ts
events/index.ts
events/ready.ts
events/voiceStateUpdate.ts
index.ts
modules/loggers/logGuildBanAdd.ts
modules/loggers/logGuildBanRemove.ts
modules/loggers/logMessageDelete.ts
modules/loggers/logMessageEdit.ts
modules/loggers/logServerJoins.ts
modules/loggers/logServerLeaves.ts
modules/loggers/logVoiceStateUpdate.ts
modules/presence/presence.ts

finally got to cleaning up logs
- added vc, ban, unban logs
- msg delete and server kick logs now properly show the operator if applicable (aka a server mod deletes a user's message, or kicks them)

more + improved logs

---

commands/BNsite/bn.ts
commands/BNsite/subcommands/bn/bnInfo.ts
commands/BNsite/subcommands/bn/bnRules.ts
commands/management/subcommands/verification/sync.ts
database/index.ts
database/schemas/bnRule.ts
events/interactionCreate.ts
helpers/core/slashCommandHandler.ts
modules/bancho/commands/verify.ts
modules/tracking/handleBnRulesButton.ts
modules/tracking/qatTracking.ts
modules/verification/client/GenerateAuthToken.ts
modules/verification/client/sendAccountValidation.ts
modules/verification/client/validateAccountValidationRequest.ts

Add bn rules support

---

commands/management/subcommands/report/reportSetDisabled.ts
commands/management/subcommands/report/reportSetPing.ts
commands/management/subcommands/setRoles/setRolesAddPreset.ts
commands/management/subcommands/setRoles/setRolesRemovePreset.ts
commands/osu/mappertracker.ts
commands/osu/subcommands/beatmap/searchBeatmap.ts
commands/osu/subcommands/maptracker/listTracker.ts
commands/osu/subcommands/maptracker/newTracker.ts
commands/osu/subcommands/maptracker/removeTracker.ts
events/CommandsManager.ts
models/commands/SlashCommand.ts
models/commands/SlashCommandSubcommandGroup.ts

Fix report commands and subcommand error handler
